
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sistpolizas

# 2) Tus credenciales recién creadas
spring.datasource.username=uacm123
spring.datasource.password=uacm123

# 3) Dile a Hibernate que actualice el esquema
spring.jpa.hibernate.ddl-auto=update

# 4) Opcional, muestra las SQL en consola
spring.jpa.show-sql=true

spring.main.log-startup-info=true
logging.level.org.springframework.boot.autoconfigure=DEBUG
