spring.datasource.driver-class-name=org.postgresql.Driver
# muestra las SQL en consola
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=create-drop
# Hibernate que actualice el esquema
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/sistpolizas

# credenciales hay que crearlas
spring.datasource.username=uacm123
spring.datasource.password=uacm123

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
